yml 수정

diff --git a/.github/workflows/android-appium-test.yml b/.github/workflows/android-appium-test.yml
--- a/.github/workflows/android-appium-test.yml
+++ b/.github/workflows/android-appium-test.yml
@@ -15,6 +15,17 @@ jobs:
         steps:
             - uses: actions/checkout@v3
 
+            - name: Check for Gradle files
+              run: |
+                  if [ ! -f "gradlew" ]; then
+                    echo "gradlew file is missing."
+                    exit 1
+                  fi
+                  if [ ! -d "gradle/wrapper" ]; then
+                    echo "gradle wrapper directory is missing."
+                    exit 1
+                  fi
+
             - name: Set up JDK 17
               uses: actions/setup-java@v3
               with:
